import type { Metadata, Viewport } from "next";
import "./globals.css";
import { BottomNav } from "@/components/layout/BottomNav";
import { PwaRegister } from "@/components/PwaRegister";
import { UnderConstructionBanner } from "@/components/UnderConstructionBanner";
import { APP_NAME, APP_SHORT_NAME, asset } from "@/lib/config";

export const metadata: Metadata = {
  title: {
    default: APP_NAME,
    template: `%s · ${APP_SHORT_NAME}`,
  },
  description:
    "Mobile reference library of clinical protocols for healthcare professionals. Not a patient app and not a clinical decision support system.",
  // The manifest body is generated by src/app/manifest.ts. We set the link href
  // explicitly because Next's auto-injected manifest link is NOT base-path
  // aware (it would point to the domain root and 404 on a Pages subdirectory).
  manifest: asset("/manifest.webmanifest"),
  applicationName: APP_NAME,
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: APP_SHORT_NAME,
  },
  icons: {
    icon: asset("/icons/icon-192.png"),
    apple: asset("/icons/apple-touch-icon.png"),
  },
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  themeColor: "#256d70",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="it">
      <body>
        {/* Fixed "work in progress" banner (h-8); content is offset by pt-8. */}
        <UnderConstructionBanner />
        <div className="mx-auto flex min-h-dvh max-w-app flex-col pt-8">
          {/* Content area leaves room for the fixed bottom nav. */}
          <main className="flex-1 pb-24">{children}</main>
        </div>
        <BottomNav />
        <PwaRegister />
      </body>
    </html>
  );
}
